apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: medical-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS db_medical
      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    USE db_medical;

    CREATE TABLE IF NOT EXISTS doctors (
      id BIGINT NOT NULL AUTO_INCREMENT,
      name VARCHAR(255) NOT NULL,
      specialty VARCHAR(255) NOT NULL,
      PRIMARY KEY (id),
      UNIQUE KEY uk_doctor_name_specialty (name, specialty)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    INSERT IGNORE INTO doctors (name, specialty) VALUES
      ('Juan Perez','Cardiologia'),
      ('Daniel Florez','Cardiología'),
      ('Yesid Lopez','Pediatría'),
      ('David Herazo','Dermatología');
