apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: medical-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS db_medical;
    USE db_medical;
    CREATE TABLE IF NOT EXISTS doctors (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      specialty VARCHAR(100) NOT NULL
    );
    INSERT INTO doctors (name, specialty) VALUES ('Juan Pérez', 'Cardiología');
