server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/db_medical?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: ${MYSQL_PASSWORD:netect123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # conserva datos entre reinicios
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: mysql
      encoding: UTF-8

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: false
  packages-to-scan: com.netec.medical.controller
